In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\acer\anaconda3\lib\site-packages (1.5.12)
Requirement already satisfied: python-dateutil in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (2.8.1)
Requirement already satisfied: tqdm in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (4.50.2)
Requirement already satisfied: urllib3 in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (1.25.11)
Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (2.24.0)
Requirement already satisfied: python-slugify in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: six>=1.10 in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in c:\users\acer\anaconda3\lib\site-packages (from kaggle) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\acer\anaconda3\lib\site-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\acer\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)

In [4]:
!kaggle datasets list -s "goal leagues"

ref                                                      title                                   size  lastUpdated          downloadCount  voteCount  usabilityRating
-------------------------------------------------------  -------------------------------------  -----  -------------------  -------------  ---------  ---------------
shreyanshkhandelwal/goal-dataset-top-5-european-leagues  Goal Dataset - Top 5 European Leagues  174KB  2021-05-23 21:20:09           1907         11  0.5294118

In [5]:
import pandas as pd
import numpy as np

In [40]:
path = "epl-goalScorer(20-21).csv"
df = pd.read_csv(path)

In [41]:
print(df)

     Unnamed: 0    id             player_name  games  time  goals         xG  \
0             0   647              Harry Kane     35  3097     23  22.174859
1             1  1250           Mohamed Salah     37  3085     22  20.250847
2             2  1228         Bruno Fernandes     37  3117     18  16.019454
3             3   453           Son Heung-Min     37  3139     17  11.023287
4             4   822         Patrick Bamford     38  3085     17  18.401863
..          ...   ...                     ...    ...   ...    ...        ...
517         517  9415  Jaden Philogene-Bidace      1     1      0   0.000000
518         518  9423         Gaetano Berardi      2   113      0   0.074761
519         519  9524          Anthony Elanga      1    67      0   0.000000
520         520  9540             Femi Seriki      1     1      0   0.000000
521         521  9552         Tyrese Francois      1    13      0   0.000000

     assists         xA  shots  key_passes  yellow_cards  red_cards position  \
0         14   7.577094    138          49             1          0        F
1          5   6.528526    126          55             0          0    F M S
2         12  11.474996    121          95             6          0      M S
3         10   9.512992     68          75             0          0    F M S
4          7   3.782247    107          30             3          0      F S
..       ...        ...    ...         ...           ...        ...      ...
517        0   0.000000      0           0             0          0        S
518        0   0.000000      1           0             0          0      D S
519        0   0.000000      0           0             0          0        M
520        0   0.000000      0           0             0          0        S
521        0   0.000000      0           0             0          0        S

            team_title  npg       npxG    xGChain  xGBuildup
0            Tottenham   19  19.130183  24.995648   4.451257
1            Liverpool   16  15.683834  28.968234   9.800236
2    Manchester United    9   8.407840  26.911412  11.932285
3            Tottenham   16  10.262118  20.671916   6.608751
4                Leeds   15  16.879525  23.394953   4.131796
..                 ...  ...        ...        ...        ...
517        Aston Villa    0   0.000000   0.056044   0.056044
518              Leeds    0   0.074761   0.231278   0.231278
519  Manchester United    0   0.000000   0.000000   0.000000
520   Sheffield United    0   0.000000   0.000000   0.000000
521             Fulham    0   0.000000   0.000000   0.000000

[522 rows x 19 columns]

In [42]:
df.head ()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [43]:
df.tail ()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.0,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,518,9423,Gaetano Berardi,2,113,0,0.074761,0,0.0,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,519,9524,Anthony Elanga,1,67,0,0.000000,0,0.0,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,520,9540,Femi Seriki,1,1,0,0.000000,0,0.0,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,521,9552,Tyrese Francois,1,13,0,0.000000,0,0.0,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

In [45]:
df_tanpaid = df.iloc [:,2:]
print(df_tanpaid)

                player_name  games  time  goals         xG  assists  \
0                Harry Kane     35  3097     23  22.174859       14
1             Mohamed Salah     37  3085     22  20.250847        5
2           Bruno Fernandes     37  3117     18  16.019454       12
3             Son Heung-Min     37  3139     17  11.023287       10
4           Patrick Bamford     38  3085     17  18.401863        7
..                      ...    ...   ...    ...        ...      ...
517  Jaden Philogene-Bidace      1     1      0   0.000000        0
518         Gaetano Berardi      2   113      0   0.074761        0
519          Anthony Elanga      1    67      0   0.000000        0
520             Femi Seriki      1     1      0   0.000000        0
521         Tyrese Francois      1    13      0   0.000000        0

            xA  shots  key_passes  yellow_cards  red_cards position  \
0     7.577094    138          49             1          0        F
1     6.528526    126          55             0          0    F M S
2    11.474996    121          95             6          0      M S
3     9.512992     68          75             0          0    F M S
4     3.782247    107          30             3          0      F S
..         ...    ...         ...           ...        ...      ...
517   0.000000      0           0             0          0        S
518   0.000000      1           0             0          0      D S
519   0.000000      0           0             0          0        M
520   0.000000      0           0             0          0        S
521   0.000000      0           0             0          0        S

            team_title  npg       npxG    xGChain  xGBuildup
0            Tottenham   19  19.130183  24.995648   4.451257
1            Liverpool   16  15.683834  28.968234   9.800236
2    Manchester United    9   8.407840  26.911412  11.932285
3            Tottenham   16  10.262118  20.671916   6.608751
4                Leeds   15  16.879525  23.394953   4.131796
..                 ...  ...        ...        ...        ...
517        Aston Villa    0   0.000000   0.056044   0.056044
518              Leeds    0   0.074761   0.231278   0.231278
519  Manchester United    0   0.000000   0.000000   0.000000
520   Sheffield United    0   0.000000   0.000000   0.000000
521             Fulham    0   0.000000   0.000000   0.000000

[522 rows x 17 columns]

In [51]:
df_rapi = df_tanpaid.sort_values(by="games", ascending = False)
df_rapi.head(15)

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
204,Andrew Robertson,38,3391,1,1.437934,7,7.220492,19,65,2,0,D,Liverpool,1,1.437934,19.869482,15.435009
480,Luke Ayling,38,3400,0,1.439750,0,2.988854,24,26,7,0,D M,Leeds,0,1.439750,14.196262,11.884364
327,Matt Targett,38,3407,0,0.280304,2,2.799669,6,39,7,0,D,Aston Villa,0,0.280304,9.610859,8.203313
116,Georginio Wijnaldum,38,2961,2,2.817427,0,1.662922,31,21,1,0,M S,Liverpool,2,2.817427,13.922182,10.476277
4,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
311,Kasper Schmeichel,38,3420,0,0.000000,0,0.000000,0,0,0,0,GK,Leicester,0,0.000000,3.868818,3.868818
55,Youri Tielemans,38,3359,6,4.168204,4,3.312251,48,49,6,0,M S,Leicester,4,2.645866,18.975342,14.945469
40,Stuart Dallas,38,3412,8,4.457074,2,2.084683,48,26,7,0,D M,Leeds,8,4.457074,18.534344,13.809802
296,Hugo Lloris,38,3420,0,0.000000,0,0.000000,0,0,0,0,GK,Tottenham,0,0.000000,4.801015,4.801015
378,Emiliano Martinez,38,3420,0,0.000000,0,0.122923,0,2,1,0,GK,Aston Villa,0,0.000000,3.730909,3.607986
110,Pierre-Emile Højbjerg,38,3420,2,1.137927,4,1.755895,14,16,9,0,M,Tottenham,2,1.137927,16.205809,14.680379
1,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
106,John McGinn,37,3330,3,2.166595,5,3.501758,45,42,12,0,M,Aston Villa,3,2.166595,14.868267,9.945619
25,Tomas Soucek,37,3330,10,8.936490,1,2.329664,63,17,7,1,M,West Ham,10,8.936490,16.730340,8.610449
87,Ashley Westwood,37,3322,3,1.005990,3,6.352089,19,49,7,0,M,Burnley,3,1.005990,10.010638,6.287275

In [50]:
df_tanpaid.describe(include='all')

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
count,522,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522,522,522.000000,522.000000,522.000000,522.000000
unique,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,28,NaN,NaN,NaN,NaN
top,Seamus Coleman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M S,Everton,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106,28,NaN,NaN,NaN,NaN
mean,NaN,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,NaN,NaN,1.668582,1.821450,5.663368,3.455060
std,NaN,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,NaN,NaN,2.909929,2.931176,5.600249,3.376584
min,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
25%,NaN,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,NaN,NaN,0.000000,0.074668,1.191391,0.720353
50%,NaN,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,NaN,NaN,0.500000,0.715585,4.252738,2.656397
75%,NaN,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,NaN,NaN,2.000000,1.945799,8.308002,5.254647
max,NaN,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,NaN,NaN,19.000000,19.130183,28.968234,18.323006

In [53]:
df_rapi[['goals', 'games', 'assists', 'shots']].mean()

goals       1.862069
games      19.643678
assists     1.289272
shots      17.379310
dtype: float64

In [55]:
df_rapi[['team_title']].mode()

             team_title
0               Everton
1  West Bromwich Albion

In [58]:
df_rapi = df_tanpaid.sort_values(by="team_title", ascending = True)
df_rapi.tail(50)

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
211,Said Benrahma,29,1361,1,2.382795,6,5.114556,34,27,0,0,M S,West Ham,1,2.382795,10.291037,3.779581
495,Vladimir Coufal,33,2966,0,1.399149,6,6.037049,15,44,3,0,D M,West Ham,0,1.399149,14.375003,8.324509
20,Michail Antonio,25,1923,10,14.138839,5,3.034945,63,25,3,0,F S,West Ham,10,14.138839,18.998891,2.655064
85,Angelo Ogbonna,27,2403,3,1.696074,0,0.428471,13,4,5,0,D,West Ham,3,1.696074,3.929544,3.707049
282,Darren Randolph,3,270,0,0.000000,0,0.000000,0,0,0,0,GK,West Ham,0,0.000000,0.275162,0.275162
356,Arthur Masuaku,12,1017,0,0.429026,2,2.595892,6,11,2,0,D M,West Ham,0,0.429026,4.273891,1.791140
25,Tomas Soucek,37,3330,10,8.936490,1,2.329664,63,17,7,1,M,West Ham,10,8.936490,16.730340,8.610449
95,Pablo Fornals,32,2513,3,5.854255,3,2.054639,46,28,3,0,F M S,West Ham,3,5.854255,14.868231,8.320600
90,Craig Dawson,21,1835,3,2.692452,0,0.054468,15,2,3,1,D,West Ham,3,2.692452,2.926758,2.926758
339,Felipe Anderson,2,2,0,0.000000,0,0.000000,0,0,0,0,S,West Ham,0,0.000000,0.050369,0.050369
304,Lukasz Fabianski,34,3060,0,0.000000,0,0.000000,0,0,2,0,GK,West Ham,0,0.000000,1.189128,1.189128
133,Issa Diop,17,1378,2,0.953531,0,0.017780,3,1,3,0,D S,West Ham,2,0.953531,2.147921,1.831723
217,Declan Rice,31,2790,1,2.557831,1,1.978934,26,23,2,0,M,West Ham,0,1.035493,10.226696,9.110460
224,Ben Johnson,14,506,1,0.484410,0,0.385866,3,4,1,0,D M S,West Ham,1,0.484410,1.443990,0.667888
281,Aaron Cresswell,35,3086,0,0.883464,8,7.347331,19,57,3,0,D,West Ham,0,0.883464,10.609667,8.381824
104,Sébastien Haller,16,933,3,2.554668,0,1.134868,25,10,0,0,F S,West Ham,3,2.554668,3.660330,0.852949
280,Mark Noble,20,697,0,0.052679,0,0.176331,1,5,1,0,M S,West Ham,0,0.052679,0.776315,0.723636
169,Manuel Lanzini,17,548,1,0.971057,1,1.001792,12,11,1,0,M S,West Ham,1,0.971057,3.232661,1.579505
236,Fabián Balbuena,14,1197,1,1.097825,0,0.000000,8,0,1,1,D S,West Ham,1,1.097825,2.218800,1.996305
33,Jarrod Bowen,37,2514,8,7.817086,5,4.952178,53,28,0,0,F M S,West Ham,8,7.817086,14.000131,3.096995
235,Ryan Fredericks,14,563,1,0.214337,1,1.298735,4,12,2,0,D M S,West Ham,1,0.214337,1.061932,0.308017
27,Jesse Lingard,15,1344,9,5.095250,4,2.329288,39,18,3,0,F M,West Ham,8,3.572913,9.868648,5.617283
405,Andriy Yarmolenko,15,343,0,0.310008,1,0.781444,7,5,3,0,M S,West Ham,0,0.310008,1.453731,0.931392
227,Rayan Ait Nouri,20,1326,1,0.475547,1,0.790439,15,14,0,0,D M S,Wolverhampton Wanderers,1,0.475547,2.692103,2.285054
238,Leander Dendoncker,32,2435,1,3.381599,0,0.581333,31,17,3,0,D M S,Wolverhampton Wanderers,1,3.381599,8.118032,5.303795
318,John Ruddy,2,91,0,0.000000,0,0.000000,0,0,0,0,GK S,Wolverhampton Wanderers,0,0.000000,0.000000,0.000000
119,Adama Traoré,36,2604,2,1.995262,2,5.228081,41,54,4,0,D F M S,Wolverhampton Wanderers,2,1.995262,9.373142,3.006398
233,Morgan Gibbs-White,10,370,1,0.735049,0,0.370324,8,7,0,0,F M S,Wolverhampton Wanderers,1,0.735049,1.575254,0.805779
108,Daniel Podence,24,1718,3,2.744378,2,1.839433,32,21,3,0,F M S,Wolverhampton Wanderers,3,2.744378,6.725103,2.910881
232,Conor Coady,36,3215,1,1.445030,0,0.196238,7,3,5,0,D,Wolverhampton Wanderers,1,1.445030,4.858107,4.689755
471,Ki-Jana Hoever,12,568,0,0.057456,0,0.184253,1,3,1,0,D S,Wolverhampton Wanderers,0,0.057456,1.222544,1.020938
364,Jonny,7,505,0,0.051705,0,0.050901,1,2,0,0,D,Wolverhampton Wanderers,0,0.051705,0.333494,0.230888
98,Romain Saiss,26,2319,3,3.099968,0,0.648440,27,4,2,0,D,Wolverhampton Wanderers,3,3.099968,4.538973,3.720983
468,Oskar Buur,1,20,0,0.000000,0,0.000000,0,0,0,0,S,Wolverhampton Wanderers,0,0.000000,0.000000,0.000000
464,Owen Otasowie,6,186,0,0.745342,1,0.388769,4,2,1,0,M S,Wolverhampton Wanderers,0,0.745342,1.382754,0.301533
210,João Moutinho,32,2456,1,0.502775,1,1.578640,14,43,3,1,M S,Wolverhampton Wanderers,1,0.502775,6.857966,6.075556
208,Willian José,16,1059,1,1.346107,0,1.271105,18,12,0,0,F S,Wolverhampton Wanderers,1,1.346107,1.988049,0.719259
435,Max Kilman,18,1291,0,0.308016,1,0.313058,6,5,4,0,D S,Wolverhampton Wanderers,0,0.308016,2.029524,1.835228
422,Rúben Vinagre,2,173,0,0.000000,0,0.000000,0,0,0,0,D S,Wolverhampton Wanderers,0,0.000000,0.178747,0.178747
420,Rui Patrício,36,3240,0,0.000000,0,0.000000,0,0,1,0,GK,Wolverhampton Wanderers,0,0.000000,1.227287,1.227287
486,Vitinha,19,500,0,0.664911,1,0.720135,8,12,0,0,M S,Wolverhampton Wanderers,0,0.664911,1.945695,1.477344
62,Pedro Neto,31,2570,5,5.494996,6,5.738268,62,61,4,0,F M S,Wolverhampton Wanderers,5,5.494996,11.516662,4.206935
401,Nélson Semedo,33,2904,0,1.176743,1,0.819633,22,19,5,0,D M,Wolverhampton Wanderers,0,1.176743,7.286725,5.929642
64,Rúben Neves,35,2591,5,4.715056,1,2.002833,65,32,7,0,M S,Wolverhampton Wanderers,2,2.431550,6.769232,4.476360
72,Raúl Jiménez,10,824,4,2.360910,0,0.632963,26,6,0,0,F,Wolverhampton Wanderers,4,2.360910,3.684076,1.233211
391,Fernando Marçal,12,609,0,0.074555,0,0.127292,2,3,2,0,D M S,Wolverhampton Wanderers,0,0.074555,1.987866,1.821051
381,Patrick Cutrone,2,21,0,0.071458,0,0.000000,1,0,0,0,S,Wolverhampton Wanderers,0,0.071458,0.071458,0.000000
80,Fabio Silva,31,1251,4,5.958539,2,1.035431,45,10,2,0,F S,Wolverhampton Wanderers,3,5.197370,4.897674,1.070238
502,Theo Corbeanu,1,7,0,0.000000,0,0.023470,0,1,0,0,S,Wolverhampton Wanderers,0,0.000000,0.023470,0.000000
231,Willy Boly,20,1790,1,1.117670,1,0.551295,14,3,1,0,D,Wolverhampton Wanderers,1,1.117670,2.684216,2.521660

In [59]:
df_rapi = df_tanpaid.sort_values(by="player_name", ascending = True)
df_rapi.head(50)

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
154,Aaron Connolly,16,755,2,4.412464,1,0.149897,22,5,0,0,F M S,Brighton,2,4.412464,4.720931,0.191225
281,Aaron Cresswell,35,3086,0,0.883464,8,7.347331,19,57,3,0,D,West Ham,0,0.883464,10.609667,8.381824
390,Aaron Ramsdale,37,3330,0,0.000000,0,0.053571,0,1,1,0,GK,Sheffield United,0,0.000000,2.794618,2.741047
139,Aaron Wan-Bissaka,34,3060,2,0.932454,4,2.547663,7,31,3,0,D,Manchester United,2,0.932454,12.242123,9.676275
126,Abdoulaye Doucouré,28,2409,2,2.369523,3,2.381616,18,20,6,0,M,Everton,2,2.369523,10.355722,6.733990
380,Aboubakar Kamara,11,303,0,0.654920,0,0.328969,4,6,1,1,F M S,Fulham,0,0.654920,1.103215,0.182326
163,Adam Lallana,29,1528,1,1.614306,1,2.628758,22,25,0,0,F M S,Brighton,1,1.614306,9.719970,5.874305
242,Adam Webster,28,2506,1,1.272957,0,0.253216,25,5,4,0,D,Brighton,1,1.272957,7.623944,7.481681
119,Adama Traoré,36,2604,2,1.995262,2,5.228081,41,54,4,0,D F M S,Wolverhampton Wanderers,2,1.995262,9.373142,3.006398
75,Ademola Lookman,34,2765,4,6.251116,4,5.258407,69,61,5,0,F M S,Fulham,4,5.489947,15.355220,7.334159
278,Adrián,3,270,0,0.000000,0,0.000000,0,0,0,0,GK,Liverpool,0,0.000000,0.397439,0.397439
345,Ahmed Elmohamady,14,823,0,0.341273,0,0.989466,9,13,2,0,D S,Aston Villa,0,0.341273,2.426968,1.610212
377,Ahmed Hegazy,1,90,0,0.000000,0,0.000000,0,0,0,0,D,West Bromwich Albion,0,0.000000,0.184028,0.184028
355,Ainsley Maitland-Niles,26,1719,0,0.796191,0,0.821991,12,6,2,0,D M S,"Arsenal,West Bromwich Albion",0,0.796191,5.968474,5.051884
88,Aleksandar Mitrovic,27,1369,3,5.677363,3,2.924711,59,23,3,0,F S,Fulham,2,4.155025,7.808299,1.849482
166,Alex Iwobi,29,1505,1,0.843632,2,2.155349,15,16,0,0,D F M S,Everton,1,0.843632,7.218916,4.475585
295,Alex McCarthy,29,2610,0,0.000000,0,0.000000,0,0,2,0,GK,Southampton,0,0.000000,2.657730,2.657730
192,Alex Oxlade-Chamberlain,13,238,1,0.300651,1,0.301778,8,2,0,0,F M S,Liverpool,1,0.300651,0.998663,0.766685
359,Alex Telles,8,606,0,0.124509,2,0.752914,4,11,0,0,D S,Manchester United,0,0.124509,2.791853,2.711231
476,Alexandre Jankewitz,2,2,0,0.000000,0,0.000000,0,0,0,1,M S,Southampton,0,0.000000,0.092009,0.092009
9,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941
254,Alexis Mac Allister,20,1044,1,1.353141,1,1.870868,24,15,1,0,F M S,Brighton,1,1.353141,5.543473,3.155042
418,Alireza Jahanbakhsh,20,466,0,1.873219,1,3.133563,18,9,3,0,D F M S,Brighton,0,1.873219,5.288836,2.521949
198,Alisson,33,2970,1,0.107682,0,0.000000,1,0,1,0,GK,Liverpool,1,0.107682,3.559325,3.559325
342,Allan,23,1961,0,0.241721,0,0.668276,7,15,6,0,M S,Everton,0,0.241721,8.989606,8.348410
81,Allan Saint-Maximin,25,1578,3,2.825913,4,4.013324,30,29,0,0,F M S,Newcastle United,3,2.825913,10.594720,4.224003
508,Allan Tchaptchet,1,10,0,0.000000,0,0.000000,0,0,0,0,S,Southampton,0,0.000000,0.000000,0.000000
365,Alphonse Areola,36,3240,0,0.000000,0,0.000000,0,0,2,0,GK,Fulham,0,0.000000,3.555330,3.555330
461,Amad Diallo Traore,2,85,0,0.000000,1,0.054055,0,1,0,0,M S,Manchester United,0,0.000000,0.054055,0.000000
500,Andi Zeqiri,9,138,0,1.025948,0,0.112493,7,1,0,0,S,Brighton,0,1.025948,0.829777,0.485276
268,Andreas Christensen,17,1375,0,0.129408,0,0.250105,3,6,2,1,D S,Chelsea,0,0.129408,7.441711,7.276742
204,Andrew Robertson,38,3391,1,1.437934,7,7.220492,19,65,2,0,D,Liverpool,1,1.437934,19.869482,15.435009
405,Andriy Yarmolenko,15,343,0,0.310008,1,0.781444,7,5,3,0,M S,West Ham,0,0.310008,1.453731,0.931392
185,Andros Townsend,34,2255,1,2.471998,5,4.146494,36,40,0,0,F M S,Crystal Palace,1,2.471998,7.262479,3.630242
367,André Gomes,28,1574,0,0.427129,1,1.054451,14,15,3,0,M S,Everton,0,0.427129,5.508419,4.376287
170,Andy Carroll,18,369,1,0.603317,0,0.063020,13,2,1,0,F S,Newcastle United,1,0.603317,0.989015,0.542128
85,Angelo Ogbonna,27,2403,3,1.696074,0,0.428471,13,4,5,0,D,West Ham,3,1.696074,3.929544,3.707049
519,Anthony Elanga,1,67,0,0.000000,0,0.000000,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
462,Anthony Gordon,3,87,0,0.000000,0,0.019140,0,1,0,0,M S,Everton,0,0.000000,0.188505,0.188505
69,Anthony Martial,22,1494,4,7.405651,3,2.619803,42,17,0,1,F M S,Manchester United,4,7.405651,11.814813,3.319505
493,Antonee Robinson,28,2158,0,0.467749,0,2.032745,10,29,4,1,D M S,Fulham,0,0.467749,7.802951,6.396044
206,Antonio Rüdiger,19,1710,1,1.139936,0,0.305807,14,4,0,0,D,Chelsea,1,1.139936,9.137650,9.044836
504,Antwoine Hackford,1,4,0,0.103445,0,0.000000,1,0,0,0,S,Sheffield United,0,0.103445,0.111831,0.008386
24,Anwar El Ghazi,28,1612,10,9.037518,0,1.882866,64,26,2,0,F M S,Aston Villa,6,5.992842,7.845563,2.691346
356,Arthur Masuaku,12,1017,0,0.429026,2,2.595892,6,11,2,0,D M,West Ham,0,0.429026,4.273891,1.791140
100,Ashley Barnes,21,1341,3,3.874066,0,0.800548,38,19,4,0,F M S,Burnley,2,3.112897,4.190315,1.198629
87,Ashley Westwood,37,3322,3,1.005990,3,6.352089,19,49,7,0,M,Burnley,3,1.005990,10.010638,6.287275
332,Axel Tuanzebe,8,311,0,0.000000,0,0.000000,0,0,2,0,D S,Manchester United,0,0.000000,0.669896,0.669896
370,Aymeric Laporte,16,1335,0,0.842340,0,0.577895,6,5,1,0,D S,Manchester City,0,0.842340,6.243810,6.243810
115,Ayoze Pérez,25,1326,2,4.036575,1,1.248606,31,23,2,0,F M S,Leicester,2,4.036575,9.872759,6.759956